"""cube quality signal fields

Revision ID: 0e18d2d36e3b
Revises: e77df8df2220
Create Date: 2026-08-13 20:02:32.303170
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0e18d2d36e3b'
down_revision: str | None = 'e77df8df2220'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default set explicitly (autogenerate doesn't add one) -
    # popular_cubes already has ~150k real rows, so a plain NOT NULL ADD
    # COLUMN with no default would fail outright rather than backfill.
    op.add_column('popular_cubes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('popular_cubes', sa.Column('featured', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('popular_cubes', sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('popular_cubes', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('popular_cubes', sa.Column('owner_follower_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('popular_cubes', 'owner_follower_count')
    op.drop_column('popular_cubes', 'version')
    op.drop_column('popular_cubes', 'keywords')
    op.drop_column('popular_cubes', 'featured')
    op.drop_column('popular_cubes', 'description')
    # ### end Alembic commands ###
