"""user settings

Revision ID: 10e23daa3300
Revises: 7bce9f3eb322
Create Date: 2026-08-09 15:46:11.509776
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '10e23daa3300'
down_revision: str | None = '7bce9f3eb322'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_comparison_mode', sa.String(length=16), nullable=False),
    sa.Column('preferred_currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###

    # Seed settings for the id=1 default user (see app.models.user.DEFAULT_USER_ID)
    # so GET /api/settings never has to get-or-create it.
    user_settings_table = sa.table(
        'user_settings',
        sa.column('user_id', sa.Integer),
        sa.column('default_comparison_mode', sa.String),
        sa.column('preferred_currency', sa.String),
    )
    op.bulk_insert(
        user_settings_table,
        [{'user_id': 1, 'default_comparison_mode': 'oracle', 'preferred_currency': 'USD'}],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
