"""functional index on lower(scryfall card name) for fast name-only resolution

Revision ID: 1cc179e8d8c1
Revises: c6505910f3b8
Create Date: 2026-08-11 09:18:41.100676
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1cc179e8d8c1'
down_revision: str | None = 'c6505910f3b8'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_scryfall_cards_name_lower', 'scryfall_cards', [sa.text('lower(name)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scryfall_cards_name_lower', table_name='scryfall_cards')
    # ### end Alembic commands ###
