"""edhrec synthesized deck cache

Revision ID: 3b31e670d773
Revises: 9b64efab99fc
Create Date: 2026-08-10 19:55:51.030624
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3b31e670d773'
down_revision: str | None = '9b64efab99fc'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edhrec_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('deck_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edhrec_synthesized_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commander_slug', sa.String(length=128), nullable=False),
    sa.Column('commander_name', sa.String(length=256), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('num_decks', sa.Integer(), nullable=False),
    sa.Column('color_identity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=False),
    sa.Column('deck_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commander_slug')
    )
    # ### end Alembic commands ###

    # Seed the id=1 sync-state singleton (see
    # app.models.edhrec.EDHREC_SYNC_STATE_ID) - same pattern as
    # deck_discovery_sync_state's id=1 seed.
    sync_state_table = sa.table(
        'edhrec_sync_state',
        sa.column('id', sa.Integer),
        sa.column('status', sa.String),
        sa.column('deck_count', sa.Integer),
    )
    op.bulk_insert(sync_state_table, [{'id': 1, 'status': 'NOT_STARTED', 'deck_count': 0}])
    op.execute("SELECT setval(pg_get_serial_sequence('edhrec_sync_state', 'id'), 1)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edhrec_synthesized_decks')
    op.drop_table('edhrec_sync_state')
    # ### end Alembic commands ###
