"""cubecobra numDecks and dateLastUpdated

Revision ID: 50fa57361063
Revises: af5420796c66
Create Date: 2026-08-12 07:35:39.340094
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '50fa57361063'
down_revision: str | None = 'af5420796c66'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular_cubes', sa.Column('num_decks', sa.Integer(), nullable=True))
    op.add_column('popular_cubes', sa.Column('date_last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('popular_cubes', 'date_last_updated')
    op.drop_column('popular_cubes', 'num_decks')
    # ### end Alembic commands ###
