"""initial schema: users, collections, collection_items, imports, import_rows

Revision ID: 518d65b42f49
Revises: 
Create Date: 2026-08-09 14:03:30.421601
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '518d65b42f49'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_collections_user_id_name')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_of_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of_import_id'], ['imports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imports_collection_id'), 'imports', ['collection_id'], unique=False)
    op.create_index(op.f('ix_imports_file_hash'), 'imports', ['file_hash'], unique=False)
    op.create_index(op.f('ix_imports_user_id'), 'imports', ['user_id'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=256), nullable=False),
    sa.Column('set_code', sa.String(length=16), nullable=True),
    sa.Column('set_name', sa.String(length=128), nullable=True),
    sa.Column('collector_number', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('foil', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('condition', sa.String(length=8), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_currency', sa.String(length=8), nullable=True),
    sa.Column('scryfall_id', sa.String(length=36), nullable=True),
    sa.Column('source_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_import_id'], ['imports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_items_collection_id'), 'collection_items', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_items_source_import_id'), 'collection_items', ['source_import_id'], unique=False)
    op.create_table('import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapped_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_reason', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_rows_import_id'), 'import_rows', ['import_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the id=1 default user (see app.models.user.DEFAULT_USER_ID). Single-user
    # mode (the default, see ARCHITECTURE.md "Documented default decisions") has no
    # login flow to create a user through, so every collection/import needs a
    # stable owner to attach to from the very first request.
    users_table = sa.table(
        "users",
        sa.column("id", sa.Integer),
        sa.column("username", sa.String),
        sa.column("display_name", sa.String),
    )
    op.bulk_insert(users_table, [{"id": 1, "username": "default", "display_name": "Default User"}])
    # The id column is a SERIAL (sequence-backed); bulk_insert wrote id=1 without
    # advancing that sequence, so the next auto-assigned id would collide with it.
    op.execute("SELECT setval(pg_get_serial_sequence('users', 'id'), 1)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_rows_import_id'), table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_collection_items_source_import_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_collection_id'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_imports_user_id'), table_name='imports')
    op.drop_index(op.f('ix_imports_file_hash'), table_name='imports')
    op.drop_index(op.f('ix_imports_collection_id'), table_name='imports')
    op.drop_table('imports')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_table('users')
    # ### end Alembic commands ###
