"""URL-sourced list imports: source_type/source_url

Revision ID: 750db753aa79
Revises: ffd72d48ab67
Create Date: 2026-08-10 09:41:33.304862
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '750db753aa79'
down_revision: str | None = 'ffd72d48ab67'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_lists', sa.Column('source_type', sa.String(length=32), nullable=True))
    op.add_column('list_imports', sa.Column('source_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list_imports', 'source_url')
    op.drop_column('card_lists', 'source_type')
    # ### end Alembic commands ###
