"""discover deck attributes and moxfield commander cache

Revision ID: 7583e401f3e8
Revises: 50fa57361063
Create Date: 2026-08-12 18:51:44.969654
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7583e401f3e8'
down_revision: str | None = '50fa57361063'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moxfield_commander_cache',
    sa.Column('main_card_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('main_card_id')
    )
    # server_default set explicitly (autogenerate doesn't add one) - popular_decks
    # already has ~18k real rows, so a plain NOT NULL ADD COLUMN with no
    # default would fail outright rather than backfill.
    op.add_column('popular_decks', sa.Column('commander_name', sa.String(length=256), nullable=True))
    op.add_column('popular_decks', sa.Column('has_primer', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('popular_decks', sa.Column('deck_size', sa.Integer(), nullable=True))
    op.add_column('popular_decks', sa.Column('theorycrafted', sa.Boolean(), nullable=True))
    op.add_column('popular_decks', sa.Column('comment_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('popular_decks', sa.Column('bookmark_count', sa.Integer(), nullable=True))
    op.add_column('popular_decks', sa.Column('deck_updated_at', sa.DateTime(), nullable=True))
    op.add_column('popular_decks', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('popular_decks', 'tags')
    op.drop_column('popular_decks', 'deck_updated_at')
    op.drop_column('popular_decks', 'bookmark_count')
    op.drop_column('popular_decks', 'comment_count')
    op.drop_column('popular_decks', 'theorycrafted')
    op.drop_column('popular_decks', 'deck_size')
    op.drop_column('popular_decks', 'has_primer')
    op.drop_column('popular_decks', 'commander_name')
    op.drop_table('moxfield_commander_cache')
    # ### end Alembic commands ###
