"""scryfall bulk data mirror, collection item resolution columns

Revision ID: 7bce9f3eb322
Revises: 518d65b42f49
Create Date: 2026-08-09 15:11:38.259685
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7bce9f3eb322'
down_revision: str | None = '518d65b42f49'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scryfall_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('oracle_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('set_code', sa.String(length=16), nullable=False),
    sa.Column('set_name', sa.String(length=128), nullable=False),
    sa.Column('collector_number', sa.String(length=32), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('layout', sa.String(length=32), nullable=False),
    sa.Column('mana_cost', sa.String(length=64), nullable=True),
    sa.Column('cmc', sa.Float(), nullable=True),
    sa.Column('type_line', sa.String(length=256), nullable=True),
    sa.Column('oracle_text', sa.Text(), nullable=True),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('color_identity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rarity', sa.String(length=16), nullable=True),
    sa.Column('foil', sa.Boolean(), nullable=False),
    sa.Column('nonfoil', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scryfall_cards_lang'), 'scryfall_cards', ['lang'], unique=False)
    op.create_index(op.f('ix_scryfall_cards_name'), 'scryfall_cards', ['name'], unique=False)
    op.create_index(op.f('ix_scryfall_cards_oracle_id'), 'scryfall_cards', ['oracle_id'], unique=False)
    op.create_index('ix_scryfall_cards_set_collector', 'scryfall_cards', ['set_code', 'collector_number'], unique=False)
    op.create_table('scryfall_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('bulk_data_type', sa.String(length=32), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('collection_items', sa.Column('resolved_oracle_id', sa.String(length=36), nullable=True))
    op.add_column('collection_items', sa.Column('resolved_scryfall_card_id', sa.String(length=36), nullable=True))
    op.add_column('collection_items', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_collection_items_resolved_oracle_id'), 'collection_items', ['resolved_oracle_id'], unique=False)
    op.create_index(op.f('ix_collection_items_resolved_scryfall_card_id'), 'collection_items', ['resolved_scryfall_card_id'], unique=False)
    # Named explicitly (autogenerate emits an unnamed FK here, which downgrade()
    # can't target with drop_constraint) rather than left for Postgres to name.
    op.create_foreign_key(
        'fk_collection_items_resolved_scryfall_card_id',
        'collection_items', 'scryfall_cards', ['resolved_scryfall_card_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###

    # Seed the id=1 sync-state singleton (see app.models.scryfall.SYNC_STATE_ID)
    # so the app never has to get-or-create it under concurrent requests.
    sync_state_table = sa.table(
        'scryfall_sync_state',
        sa.column('id', sa.Integer),
        sa.column('status', sa.String),
        sa.column('bulk_data_type', sa.String),
        sa.column('card_count', sa.Integer),
    )
    op.bulk_insert(sync_state_table, [{'id': 1, 'status': 'NOT_STARTED', 'bulk_data_type': 'default_cards', 'card_count': 0}])
    op.execute("SELECT setval(pg_get_serial_sequence('scryfall_sync_state', 'id'), 1)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_collection_items_resolved_scryfall_card_id', 'collection_items', type_='foreignkey')
    op.drop_index(op.f('ix_collection_items_resolved_scryfall_card_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_resolved_oracle_id'), table_name='collection_items')
    op.drop_column('collection_items', 'resolved_at')
    op.drop_column('collection_items', 'resolved_scryfall_card_id')
    op.drop_column('collection_items', 'resolved_oracle_id')
    op.drop_table('scryfall_sync_state')
    op.drop_index('ix_scryfall_cards_set_collector', table_name='scryfall_cards')
    op.drop_index(op.f('ix_scryfall_cards_oracle_id'), table_name='scryfall_cards')
    op.drop_index(op.f('ix_scryfall_cards_name'), table_name='scryfall_cards')
    op.drop_index(op.f('ix_scryfall_cards_lang'), table_name='scryfall_cards')
    op.drop_table('scryfall_cards')
    # ### end Alembic commands ###
