"""cube full-scrape state tracking

Revision ID: 88a0fd0eada6
Revises: 7583e401f3e8
Create Date: 2026-08-12 20:25:15.091673
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '88a0fd0eada6'
down_revision: str | None = '7583e401f3e8'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cube_full_scrape_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_progress_at', sa.DateTime(), nullable=True),
    sa.Column('cubes_found', sa.Integer(), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed the id=1 singleton row (see app.models.cubecobra.CUBE_FULL_SCRAPE_STATE_ID)
    # so the app never has to get-or-create it under concurrent requests -
    # same pattern as every other single-row sync-state table's migration.
    state_table = sa.table(
        'cube_full_scrape_state',
        sa.column('id', sa.Integer),
        sa.column('status', sa.String),
        sa.column('cubes_found', sa.Integer),
        sa.column('pages_fetched', sa.Integer),
    )
    op.bulk_insert(state_table, [{'id': 1, 'status': 'INACTIVE', 'cubes_found': 0, 'pages_fetched': 0}])
    op.execute("SELECT setval(pg_get_serial_sequence('cube_full_scrape_state', 'id'), 1)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cube_full_scrape_state')
    # ### end Alembic commands ###
