"""mtgjson precon deck coverage cache

Revision ID: 9a3a2e9ff4fe
Revises: fe1026355b91
Create Date: 2026-08-11 13:07:07.509565
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9a3a2e9ff4fe'
down_revision: str | None = 'fe1026355b91'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precon_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('commander_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('release_date', sa.String(length=10), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('card_count', sa.Integer(), nullable=False),
    sa.Column('cards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deck_text', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_table('precon_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('deck_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed the id=1 sync-state singleton (see
    # app.models.mtgjson_precons.PRECON_SYNC_STATE_ID) - same pattern as
    # every other discovery source's id=1 seed.
    sync_state_table = sa.table(
        'precon_sync_state',
        sa.column('id', sa.Integer),
        sa.column('status', sa.String),
        sa.column('deck_count', sa.Integer),
    )
    op.bulk_insert(sync_state_table, [{'id': 1, 'status': 'NOT_STARTED', 'deck_count': 0}])
    op.execute("SELECT setval(pg_get_serial_sequence('precon_sync_state', 'id'), 1)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('precon_sync_state')
    op.drop_table('precon_decks')
    # ### end Alembic commands ###
