"""popular deck discovery cache

Revision ID: 9b64efab99fc
Revises: d5c76d0be1dd
Create Date: 2026-08-10 18:21:02.136181
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9b64efab99fc'
down_revision: str | None = 'd5c76d0be1dd'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_discovery_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('deck_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('popular_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('color_identity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_popular_decks_source_external_id')
    )
    # ### end Alembic commands ###

    # Seed the id=1 sync-state singleton (see
    # app.models.discover.DISCOVERY_SYNC_STATE_ID) so the app never has to
    # get-or-create it under concurrent requests - same pattern as
    # scryfall_sync_state's id=1 seed.
    sync_state_table = sa.table(
        'deck_discovery_sync_state',
        sa.column('id', sa.Integer),
        sa.column('status', sa.String),
        sa.column('deck_count', sa.Integer),
    )
    op.bulk_insert(sync_state_table, [{'id': 1, 'status': 'NOT_STARTED', 'deck_count': 0}])
    op.execute("SELECT setval(pg_get_serial_sequence('deck_discovery_sync_state', 'id'), 1)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('popular_decks')
    op.drop_table('deck_discovery_sync_state')
    # ### end Alembic commands ###
