"""cube full import state tracking

Revision ID: 9ce6318a6b09
Revises: 0e18d2d36e3b
Create Date: 2026-08-14 20:58:56.562365
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9ce6318a6b09'
down_revision: str | None = '0e18d2d36e3b'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cube_full_import_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_progress_at', sa.DateTime(), nullable=True),
    sa.Column('total_candidates', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('last_cube_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed the id=1 singleton row (see app.models.cubecobra.CUBE_FULL_IMPORT_STATE_ID)
    # so the app never has to get-or-create it under concurrent requests -
    # same pattern as every other single-row sync-state table's migration.
    state_table = sa.table(
        'cube_full_import_state',
        sa.column('id', sa.Integer),
        sa.column('status', sa.String),
        sa.column('total_candidates', sa.Integer),
        sa.column('imported_count', sa.Integer),
        sa.column('failed_count', sa.Integer),
        sa.column('skipped_count', sa.Integer),
    )
    op.bulk_insert(state_table, [{
        'id': 1, 'status': 'INACTIVE', 'total_candidates': 0,
        'imported_count': 0, 'failed_count': 0, 'skipped_count': 0,
    }])
    op.execute("SELECT setval(pg_get_serial_sequence('cube_full_import_state', 'id'), 1)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cube_full_import_state')
    # ### end Alembic commands ###
