"""cube discovery server-side import tracking

Revision ID: af5420796c66
Revises: f2a55a4ecf11
Create Date: 2026-08-11 21:22:28.636116
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'af5420796c66'
down_revision: str | None = 'f2a55a4ecf11'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular_cubes', sa.Column('imported_list_id', sa.Integer(), nullable=True))
    op.add_column('popular_cubes', sa.Column('import_error', sa.String(length=1024), nullable=True))
    op.add_column('popular_cubes', sa.Column('import_attempted_at', sa.DateTime(), nullable=True))
    # Named explicitly (autogenerate emits an unnamed FK here, which
    # downgrade() can't target with drop_constraint) rather than left for
    # Postgres to name.
    op.create_foreign_key(
        'fk_popular_cubes_imported_list_id',
        'popular_cubes', 'card_lists', ['imported_list_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_popular_cubes_imported_list_id', 'popular_cubes', type_='foreignkey')
    op.drop_column('popular_cubes', 'import_attempted_at')
    op.drop_column('popular_cubes', 'import_error')
    op.drop_column('popular_cubes', 'imported_list_id')
    # ### end Alembic commands ###
