"""cubecobra popular cube discovery cache

Revision ID: c6505910f3b8
Revises: d8b8d98692bc
Create Date: 2026-08-11 08:14:35.741967
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c6505910f3b8'
down_revision: str | None = 'd8b8d98692bc'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cube_discovery_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('cube_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('popular_cubes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('short_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('owner_username', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('card_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    # ### end Alembic commands ###

    # Seed the id=1 sync-state singleton (see
    # app.models.cubecobra.CUBE_DISCOVERY_SYNC_STATE_ID) - same pattern as
    # deck_discovery_sync_state's id=1 seed.
    sync_state_table = sa.table(
        'cube_discovery_sync_state',
        sa.column('id', sa.Integer),
        sa.column('status', sa.String),
        sa.column('cube_count', sa.Integer),
    )
    op.bulk_insert(sync_state_table, [{'id': 1, 'status': 'NOT_STARTED', 'cube_count': 0}])
    op.execute("SELECT setval(pg_get_serial_sequence('cube_discovery_sync_state', 'id'), 1)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('popular_cubes')
    op.drop_table('cube_discovery_sync_state')
    # ### end Alembic commands ###
