"""card lists (deck/cube) and list import pipeline

Revision ID: c7d8926ab5a8
Revises: 10e23daa3300
Create Date: 2026-08-09 16:05:08.100322
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c7d8926ab5a8'
down_revision: str | None = '10e23daa3300'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('list_type', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_card_lists_user_id_name')
    )
    op.create_index(op.f('ix_card_lists_user_id'), 'card_lists', ['user_id'], unique=False)
    op.create_table('list_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_of_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_import_id'], ['list_imports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_id'], ['card_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_imports_file_hash'), 'list_imports', ['file_hash'], unique=False)
    op.create_index(op.f('ix_list_imports_list_id'), 'list_imports', ['list_id'], unique=False)
    op.create_index(op.f('ix_list_imports_user_id'), 'list_imports', ['user_id'], unique=False)
    op.create_table('card_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=256), nullable=False),
    sa.Column('set_code', sa.String(length=16), nullable=True),
    sa.Column('set_name', sa.String(length=128), nullable=True),
    sa.Column('collector_number', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('foil', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('scryfall_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_oracle_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_scryfall_card_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('source_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['card_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_scryfall_card_id'], ['scryfall_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_import_id'], ['list_imports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_list_items_list_id'), 'card_list_items', ['list_id'], unique=False)
    op.create_index(op.f('ix_card_list_items_resolved_oracle_id'), 'card_list_items', ['resolved_oracle_id'], unique=False)
    op.create_index(op.f('ix_card_list_items_resolved_scryfall_card_id'), 'card_list_items', ['resolved_scryfall_card_id'], unique=False)
    op.create_index(op.f('ix_card_list_items_source_import_id'), 'card_list_items', ['source_import_id'], unique=False)
    op.create_table('list_import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_import_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapped_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_reason', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['list_import_id'], ['list_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_import_rows_list_import_id'), 'list_import_rows', ['list_import_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_list_import_rows_list_import_id'), table_name='list_import_rows')
    op.drop_table('list_import_rows')
    op.drop_index(op.f('ix_card_list_items_source_import_id'), table_name='card_list_items')
    op.drop_index(op.f('ix_card_list_items_resolved_scryfall_card_id'), table_name='card_list_items')
    op.drop_index(op.f('ix_card_list_items_resolved_oracle_id'), table_name='card_list_items')
    op.drop_index(op.f('ix_card_list_items_list_id'), table_name='card_list_items')
    op.drop_table('card_list_items')
    op.drop_index(op.f('ix_list_imports_user_id'), table_name='list_imports')
    op.drop_index(op.f('ix_list_imports_list_id'), table_name='list_imports')
    op.drop_index(op.f('ix_list_imports_file_hash'), table_name='list_imports')
    op.drop_table('list_imports')
    op.drop_index(op.f('ix_card_lists_user_id'), table_name='card_lists')
    op.drop_table('card_lists')
    # ### end Alembic commands ###
