"""price cache: price observations and price profiles

Revision ID: ccfde7176111
Revises: d7d713f87bdf
Create Date: 2026-08-10 14:38:32.362856
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ccfde7176111'
down_revision: str | None = 'd7d713f87bdf'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scryfall_card_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('foil', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scryfall_card_id'], ['scryfall_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scryfall_card_id', 'provider', 'currency', 'foil', name='uq_price_observations_card_provider_currency_foil')
    )
    op.create_index(op.f('ix_price_observations_scryfall_card_id'), 'price_observations', ['scryfall_card_id'], unique=False)
    op.create_table('price_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('provider_priority', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prefer_foil', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_price_profiles_user_id_name')
    )
    op.create_index(op.f('ix_price_profiles_user_id'), 'price_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_profiles_user_id'), table_name='price_profiles')
    op.drop_table('price_profiles')
    op.drop_index(op.f('ix_price_observations_scryfall_card_id'), table_name='price_observations')
    op.drop_table('price_observations')
    # ### end Alembic commands ###
