"""scryfall printed_name column, switch to all_cards

Revision ID: d564615e71f8
Revises: c7d8926ab5a8
Create Date: 2026-08-09 20:47:55.340480
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd564615e71f8'
down_revision: str | None = 'c7d8926ab5a8'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scryfall_cards', sa.Column('printed_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###

    # The existing mirror was synced from default_cards, which has no
    # printed_name for most non-English cards (see app.models.scryfall
    # module docstring) - reset to NOT_STARTED so the existing auto-sync
    # mechanism (app.services.scryfall_service.maybe_auto_trigger_sync) picks
    # up a fresh all_cards sync on the next backend start, same as a
    # brand-new install would. A manual "Sync now" on the System Status page
    # works immediately too, without waiting for a restart.
    op.execute("UPDATE scryfall_sync_state SET bulk_data_type = 'all_cards', status = 'NOT_STARTED' WHERE id = 1")


def downgrade() -> None:
    op.execute("UPDATE scryfall_sync_state SET bulk_data_type = 'default_cards' WHERE id = 1")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scryfall_cards', 'printed_name')
    # ### end Alembic commands ###
