"""price sync state table

Revision ID: d5c76d0be1dd
Revises: ccfde7176111
Create Date: 2026-08-10 14:44:42.889853
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd5c76d0be1dd'
down_revision: str | None = 'ccfde7176111'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_sync_state',
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('price_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('provider')
    )
    # ### end Alembic commands ###

    # Seed the 'mtgjson' row (see app.models.pricing.PriceSyncState) so the
    # app never has to get-or-create it under concurrent requests - same
    # pattern as scryfall_sync_state's id=1 singleton seed. No SERIAL
    # sequence to fix up here - 'provider' is a plain string primary key.
    sync_state_table = sa.table(
        'price_sync_state',
        sa.column('provider', sa.String),
        sa.column('status', sa.String),
        sa.column('price_count', sa.Integer),
    )
    op.bulk_insert(sync_state_table, [{'provider': 'mtgjson', 'status': 'NOT_STARTED', 'price_count': 0}])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_sync_state')
    # ### end Alembic commands ###
