"""card list refresh status tracking

Revision ID: d7d713f87bdf
Revises: 750db753aa79
Create Date: 2026-08-10 09:52:50.959316
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd7d713f87bdf'
down_revision: str | None = '750db753aa79'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_lists', sa.Column('refresh_status', sa.String(length=32), nullable=True))
    op.add_column('card_lists', sa.Column('refresh_error', sa.String(length=1024), nullable=True))
    op.add_column('card_lists', sa.Column('last_refreshed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_lists', 'last_refreshed_at')
    op.drop_column('card_lists', 'refresh_error')
    op.drop_column('card_lists', 'refresh_status')
    # ### end Alembic commands ###
