"""add grafana embed url setting

Revision ID: d8b8d98692bc
Revises: 3b31e670d773
Create Date: 2026-08-10 21:29:12.574415
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd8b8d98692bc'
down_revision: str | None = '3b31e670d773'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('grafana_embed_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'grafana_embed_url')
    # ### end Alembic commands ###
