"""cube full-scrape resume cursor

Revision ID: e77df8df2220
Revises: 88a0fd0eada6
Create Date: 2026-08-13 17:14:46.317229
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e77df8df2220'
down_revision: str | None = '88a0fd0eada6'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cube_full_scrape_state', sa.Column('last_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cube_full_scrape_state', 'last_key')
    # ### end Alembic commands ###
