"""lazy pricing cache columns on popular decks

Revision ID: f2a55a4ecf11
Revises: 9a3a2e9ff4fe
Create Date: 2026-08-11 16:06:01.428549
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f2a55a4ecf11'
down_revision: str | None = '9a3a2e9ff4fe'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular_decks', sa.Column('coverage_percent', sa.Float(), nullable=True))
    op.add_column('popular_decks', sa.Column('missing_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('popular_decks', sa.Column('missing_cost_currency', sa.String(length=3), nullable=True))
    op.add_column('popular_decks', sa.Column('unpriced_missing_count', sa.Integer(), nullable=True))
    op.add_column('popular_decks', sa.Column('priced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('popular_decks', 'priced_at')
    op.drop_column('popular_decks', 'unpriced_missing_count')
    op.drop_column('popular_decks', 'missing_cost_currency')
    op.drop_column('popular_decks', 'missing_cost')
    op.drop_column('popular_decks', 'coverage_percent')
    # ### end Alembic commands ###
