"""add bracket to popular decks

Revision ID: fe1026355b91
Revises: 1cc179e8d8c1
Create Date: 2026-08-11 10:29:23.425189
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'fe1026355b91'
down_revision: str | None = '1cc179e8d8c1'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular_decks', sa.Column('bracket', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('popular_decks', 'bracket')
    # ### end Alembic commands ###
