"""user settings: card_name_language

Revision ID: ffd72d48ab67
Revises: d564615e71f8
Create Date: 2026-08-09 20:48:55.089081
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ffd72d48ab67'
down_revision: str | None = 'd564615e71f8'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('card_name_language', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'card_name_language')
    # ### end Alembic commands ###
